package comnd.example.dllo.mygiftdemo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import comnd.example.dllo.mygiftdemo.db.PresentBean;

import comnd.example.dllo.mygiftdemo.db.PresentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig presentBeanDaoConfig;

    private final PresentBeanDao presentBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        presentBeanDaoConfig = daoConfigMap.get(PresentBeanDao.class).clone();
        presentBeanDaoConfig.initIdentityScope(type);

        presentBeanDao = new PresentBeanDao(presentBeanDaoConfig, this);

        registerDao(PresentBean.class, presentBeanDao);
    }
    
    public void clear() {
        presentBeanDaoConfig.getIdentityScope().clear();
    }

    public PresentBeanDao getPresentBeanDao() {
        return presentBeanDao;
    }

}
