package comnd.example.dllo.mygiftdemo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRESENT_BEAN".
 */
public class PresentBean {

    private Long id;
    private String userName;
    private String imageUrl;
    private String title;
    private String author;
    private String nextUrl;
    private String likesCount;
    private String other;
    private String others;
    private String path;
    private Boolean islike;
    private String classify;

    public PresentBean() {
    }


    public PresentBean(String path) {
        this.path = path;
    }

    public PresentBean(Long id) {
        this.id = id;
    }

    public PresentBean(Long id, String userName, String imageUrl, String title, String author, String nextUrl, String likesCount, String other, String others, String path, Boolean islike, String classify) {
        this.id = id;
        this.userName = userName;
        this.imageUrl = imageUrl;
        this.title = title;
        this.author = author;
        this.nextUrl = nextUrl;
        this.likesCount = likesCount;
        this.other = other;
        this.others = others;
        this.path = path;
        this.islike = islike;
        this.classify = classify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getNextUrl() {
        return nextUrl;
    }

    public void setNextUrl(String nextUrl) {
        this.nextUrl = nextUrl;
    }

    public String getLikesCount() {
        return likesCount;
    }

    public void setLikesCount(String likesCount) {
        this.likesCount = likesCount;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getOthers() {
        return others;
    }

    public void setOthers(String others) {
        this.others = others;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Boolean getIslike() {
        return islike;
    }

    public void setIslike(Boolean islike) {
        this.islike = islike;
    }

    public String getClassify() {
        return classify;
    }

    public void setClassify(String classify) {
        this.classify = classify;
    }

}
